import assert from "node:assert/strict";
import { store } from "./store.js";
const memory = new Map();
globalThis.localStorage = { getItem: (k) => memory.get(k) ?? null, setItem: (k, v) => memory.set(k, v) };
assert.equal(store.state.showFaceOutlines, false);
let outlineChange = null;
const offOutline = store.on("change:showFaceOutlines", (value) => { outlineChange = value; });
store.set({ showFaceOutlines: true });
assert.equal(outlineChange, true);
offOutline();
store.set({ model: "first" });
store.loadDraft();
assert.equal(store.canUndo(), false);
const id = store.addItem({ type: "pin", point: [0, 0, 0], note: "保存するメモ" });
assert.equal(store.canUndo(), true);
store.removeItem(id);
assert.equal(store.state.draft.items.length, 0);
store.undo();
assert.equal(store.state.draft.items[0].note, "保存するメモ");
assert.equal(store.canRedo(), true);
store.setMessage("モデル固有のメモ");
store.set({ model: "second" });
store.loadDraft();
assert.equal(store.state.draft.items.length, 0);
store.set({ model: "first" });
store.loadDraft();
assert.equal(store.state.draft.message, "モデル固有のメモ");
assert.equal(store.canUndo(), false);
memory.set("studio.draft.first", JSON.stringify({ message: null, items: [null, 5, { id: "a", type: "pin" }] }));
store.loadDraft();
assert.equal(store.state.draft.message, "");
assert.equal(store.state.draft.items.length, 1);
store.set({ layout: { kind: "plate", id: "plate-a" } });
store.loadDraft();
assert.equal(store.state.draft.items.length, 0);
store.setMessage("プレートのメモ");
store.set({ layout: { kind: "assembled" } });
store.loadDraft();
assert.equal(store.state.draft.message, "");
store.set({ layout: { kind: "plate", id: "plate-a" } });
store.set({ sectionTransform: "rotate" });
store.loadDraft();
assert.equal(store.state.draft.message, "プレートのメモ");
assert.equal(store.state.sectionTransform, "off");
assert.equal(store.canUndo(), false);
store.set({ sectionTransform: "translate" });
store.clearDraft();
assert.equal(store.state.sectionTransform, "off");
console.log("store: 18 assertions passed");
