import assert from 'node:assert/strict';import fs from 'node:fs';
import {Playback,createAssembly} from './core.mjs';import {AUTO_HOLDS,STEPS} from './steps.mjs';
const gates=Object.keys(AUTO_HOLDS).map(Number),checks=[];
function check(name,fn){fn();checks.push(name);}
check('initial stopped, first inventory dwell, one boundary per tick',()=>{const p=new Playback(29,false,gates);assert(!p.running);p.startAuto();assert.equal(p.index,0);assert.equal(p.phase,'dwell');p.tick(.3);assert.equal(p.index,0);p.tick(1000);assert.equal(p.index,1);assert.equal(p.fraction,0);p.tick(1000);assert.equal(p.index,1);assert.equal(p.phase,'dwell');});
check('motion pause and resume retain position, dwell pause retains explanation time',()=>{const p=new Playback(29,false,gates);p.seek(7);p.startAuto();p.tick(2);p.tick(1);p.pause();const f=p.fraction;p.tick(100);assert.equal(p.fraction,f);p.setSpeed(2);p.startAuto();p.tick(1);assert(p.fraction>f);p.tick(100);p.tick(.7);p.pause();const elapsed=p.dwellElapsed;p.tick(100);assert.equal(p.dwellElapsed,elapsed);p.startAuto();p.tick(.1);assert.equal(p.dwellElapsed,elapsed+.2);});
check('unresolved gates cannot automatically pass; continue is preview only',()=>{for(const gate of gates){const p=new Playback(29,false,gates);p.seek(gate-1);p.startAuto();if(p.phase==='gate')p.continuePreview();p.tick(2);p.tick(9);assert.equal(p.index,gate);assert.equal(p.phase,'gate');assert(!p.running);p.startAuto();p.tick(999);assert.equal(p.phase,'gate');p.continuePreview();assert.equal(p.phase,'dwell');assert(p.running);assert(!('physicalVerified' in p));}});
check('manual seek cancels auto and clears timers at any phase',()=>{const p=new Playback(29,false,gates);for(const i of [0,8,9,23,24,28]){p.seek(i);p.startAuto();p.tick(.3);p.seek(5);assert.equal(p.mode,'single');assert.equal(p.phase,'settled');assert.equal(p.fraction,1);assert(!p.running);assert.equal(p.dwellElapsed,0);p.tick(999);assert.equal(p.index,5);}});
check('repeated commands and speed/dwell changes do not duplicate progression',()=>{const p=new Playback(29,false,gates);p.setDwell(15);for(let i=0;i<500;i++){p.startAuto();p.startAuto();p.tick(.003);p.pause();p.pause();p.setSpeed(1+(i%4));p.setDwell(14.5+(i%2)*.5);p.startAuto();}assert.equal(p.index,0);assert(p.dwellElapsed<4);});
check('complete run visits every step in order, holds 9/23/24, stops without loop',()=>{const p=new Playback(29,false,gates);p.setSpeed(4);p.setDwell(.5);p.startAuto();const seen=[0],held=[];for(let i=0;i<3000&&p.phase!=='complete';i++){p.tick(.1);if(seen.at(-1)!==p.index)seen.push(p.index);if(p.phase==='gate'){held.push(p.index);p.continuePreview();}}assert.deepEqual(seen,Array.from({length:29},(_,i)=>i));assert.deepEqual(held,gates);assert.equal(p.index,28);assert.equal(p.fraction,1);assert(!p.running);p.tick(999);p.startAuto();p.tick(999);assert.equal(p.index,28);assert(!p.running);});
check('bypass runs all 29 steps without gates and turning it off stops at the next gate',()=>{const p=new Playback(29,false,gates);p.setBypass(true);p.setSpeed(8);p.setDwell(.5);p.startAuto();const seen=[0],held=[];for(let i=0;i<3000&&p.phase!=='complete';i++){p.tick(.1);if(seen.at(-1)!==p.index)seen.push(p.index);if(p.phase==='gate')held.push(p.index);}assert.deepEqual(seen,Array.from({length:29},(_,i)=>i));assert.deepEqual(held,[]);assert.equal(p.phase,'complete');p.setBypass(false);p.seek(22);p.startAuto();p.tick(.5);p.tick(9);assert.equal(p.index,23);assert.equal(p.phase,'gate');assert(!p.running);});
check('turning bypass on at a gate resumes preview without confirming anything',()=>{const p=new Playback(29,false,gates);p.seek(8);p.startAuto();p.tick(2);p.tick(9);assert.equal(p.phase,'gate');assert(!p.running);p.setBypass(true);assert.equal(p.phase,'dwell');assert(p.running);assert(!('physicalVerified' in p));});
check('turning bypass off preserves auto dwell position and timer',()=>{const p=new Playback(29,false,gates);p.setBypass(true);p.startAuto();p.tick(.4);const before={index:p.index,fraction:p.fraction,phase:p.phase,dwellElapsed:p.dwellElapsed,running:p.running};p.setBypass(false);assert.deepEqual({index:p.index,fraction:p.fraction,phase:p.phase,dwellElapsed:p.dwellElapsed,running:p.running},before);});
check('bypass changes preserve manual pause and seek stops',()=>{const p=new Playback(29,false,gates);p.seek(7);p.startAuto();p.tick(1);p.pause('手動');const fraction=p.fraction;p.setBypass(true);assert(!p.running);assert.equal(p.fraction,fraction);assert.equal(p.pauseReason,'手動');p.seek(12);p.setBypass(false);p.setBypass(true);assert.equal(p.index,12);assert.equal(p.phase,'settled');assert(!p.running);});
check('2x, 4x and 8x accelerate both motion and explanation dwell',()=>{for(const speed of [2,4,8]){const motion=new Playback(29,false,gates);motion.seek(1);motion.setSpeed(speed);motion.play();motion.tick(9/speed-.001);assert(motion.fraction<1);motion.tick(.002);assert.equal(motion.fraction,1);const dwell=new Playback(29,false,gates);dwell.setSpeed(speed);dwell.startAuto();dwell.tick(2/speed-.001);assert.equal(dwell.index,0);dwell.tick(.002);assert.equal(dwell.index,1);}});
check('reduced motion keeps explanation dwell and hold gates',()=>{const p=new Playback(29,true,gates);p.seek(8);p.startAuto();p.tick(2);assert.equal(p.index,9);p.tick(.01);assert.equal(p.phase,'gate');assert(!p.running);});
check('auto pause/seek/play spam keeps all mesh poses deterministic',()=>{const cad=JSON.parse(fs.readFileSync(new URL('assets/cad.json',import.meta.url))),manifest=JSON.parse(fs.readFileSync(new URL('assets/cad_parts.json',import.meta.url))),a=createAssembly(cad,manifest),before=JSON.stringify(a.snapshots),p=new Playback(29,false,gates);for(let i=0;i<1000;i++){p.seek((i*7)%29);p.startAuto();p.tick(.017);p.pause();assert.deepEqual(a.sample(p.index,p.fraction),a.sample(p.index,p.fraction));p.play();p.tick(.013);p.seek(i%29);assert.deepEqual(a.sample(p.index,1).poses,a.snapshots[p.index]);}assert.equal(JSON.stringify(a.snapshots),before);});
const result={pass:true,checks,auto_holds:gates,physical_tested:false};console.log(JSON.stringify(result,null,2));if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2));
