import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {BoxPhysics,initPhysics,DEFAULTS,rotate,S,NUMERICAL_LIMITS} from './physics.mjs';
import {B3_MODEL,createWorkspaceNav,themePalette,watchTheme} from '../shared/workspace.mjs';
const $=id=>document.getElementById(id);
let sim=null,replayIndex=null,replayPlaying=false,replayTime=0;
function pauseWork(){if(sim)sim.paused=true;replayPlaying=false;}
const workspace=createWorkspaceNav({active:'physics',model:B3_MODEL,onNavigate:pauseWork});
$('workspaceHeader').insertBefore(workspace.element,$('loading'));workspace.setModel(B3_MODEL);
for(const id of ['open','close','repeat','stop','reset','apply','step','pause'])$(id).disabled=true;
const specs=[['torqueCap','停止トルク上限 N·m',0,.245,.001],['commandSpeed','指令速度 °/s',1,120,1],['lidMassScale','蓋の質量倍率',.1,10,.1],['frontLoadG','蓋前端の追加重量 g',0,1000,1],['comShiftMm','蓋重心の前方差 mm',-10,10,.1],['friction','接触摩擦係数',0,1,.05],['bearingDamping','軸受の粘性抵抗 N·m·s/rad',0,.25,.0001],['hornBiasMm','ホーン外周寸法差 mm',-.2,.2,.05],['contactSkinMm','接触 skin mm',0,.1,.005],['initialLid','初期蓋角 °',0,65,1],['openTarget','開指令のサーボ角 °',50,65,.1],['closedTarget','閉指令のサーボ角 °',-20,0,.1],['dt','固定時間刻み s',1/1920,1/240,1/1920],['iterations','ソルバー反復数',4,32,1],['rotorInertia','回転子推定慣性 kg·m²',1e-7,2e-5,1e-7]];
for(const [key,label,min,max,step] of specs){const row=document.createElement('label');row.append(label);const input=document.createElement('input');input.type='number';input.id=key;input.min=min;input.max=max;input.step=step;input.value=DEFAULTS[key];input.addEventListener('input',()=>{$('apply').textContent='変更した条件を適用して初期化';});row.append(input);$('parameters').append(row);}
const getParams=()=>Object.fromEntries([...specs.map(([k])=>[k,Number($(k).value)]),...['contactEnabled','powered','fixedBase','shaftBlock'].map(k=>[k,$(k).checked]),['contactMode',$('contactMode').value]]);
const setParams=p=>{$('contactMode').value=p.contactMode;updateMode();for(const [k] of specs)$(k).value=p[k];for(const k of ['contactEnabled','powered','fixedBase','shaftBlock'])$(k).checked=p[k];};
const [cad,shapes]=await Promise.all(['cad.json','contact_model.json'].map(name=>fetch('assets/'+name).then(r=>{if(!r.ok)throw Error(name);return r.json();})));
await initPhysics();sim=new BoxPhysics(cad,shapes);updateMode();
const host=$('viewport'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.001,5);camera.up.set(0,0,1);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;host.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.10;controls.maxDistance=.75;
function cameraReset(){camera.position.set(.20,.20,.16);controls.target.set(.035,.036,.045);controls.update();}cameraReset();
scene.add(new THREE.HemisphereLight(0xd8e9ff,0x30363f,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-.04,.10,.23);scene.add(light);
const gridPalette=themePalette();
const grid=new THREE.GridHelper(.30,30,gridPalette.line,gridPalette.line);grid.rotation.x=Math.PI/2;grid.position.set(.035,.035,-.00005);scene.add(grid);
let activePalette=themePalette();
const disposeTheme=watchTheme(palette=>{activePalette=palette;renderer.setClearColor(palette.card,0);const gridColor=new THREE.Color(palette.line),attribute=grid.geometry.getAttribute('color');for(let i=0;i<attribute.count;i++)attribute.setXYZ(i,gridColor.r,gridColor.g,gridColor.b);attribute.needsUpdate=true;drawGraph();});
const colors={base:0xa9b5c3,frame:0x6f8095,lid:0x009e73,cup:0x0072b2,rotor:0xe69f00,link:0xcc79a7};const groups={};for(const k of Object.keys(cad.bodies)){groups[k]=new THREE.Group();scene.add(groups[k]);}
const meshes=[];
for(const p of cad.parts){const com=cad.bodies[p.group].com,verts=p.vertices.map((x,i)=>x-com[i%3]),geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(p.indices);geo.computeVertexNormals();const color=p.reference&&!p.name.includes('horn')?0x586779:colors[p.group];const mat=new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.02,flatShading:true,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,mat);mesh.userData=p;groups[p.group].add(mesh);meshes.push(mesh);}
const markerGeometry=new THREE.SphereGeometry(.0005,8,6),markerMaterial=new THREE.MeshBasicMaterial({color:0xffdd79,depthTest:false}),markerPool=[];
const markers=new THREE.Group();scene.add(markers);const axisGroup=new THREE.Group();scene.add(axisGroup);
const hingeGeo=new THREE.CylinderGeometry(.00045,.00045,.034,12);hingeGeo.rotateZ(Math.PI/2);
const axes={};for(const [key,color] of [['H',colors.lid],['O',colors.rotor],['A',colors.link],['B',colors.link]]){const mesh=new THREE.Mesh(hingeGeo,new THREE.MeshBasicMaterial({color,depthTest:false,transparent:true,opacity:.85}));mesh.renderOrder=4;axisGroup.add(mesh);axes[key]=mesh;}
const comMeshes={};for(const [key,data]of Object.entries(cad.bodies)){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.0008,10,8),new THREE.MeshBasicMaterial({color:colors[key],depthTest:false}));axisGroup.add(mesh);comMeshes[key]=mesh;}
const debug=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.65,depthTest:false}));debug.renderOrder=5;scene.add(debug);
function sceneUpdate(){if(replayIndex!==null){const row=sim.log[replayIndex];for(const [name,p]of Object.entries(row.poses)){groups[name].position.fromArray(p.translationM);groups[name].quaternion.set(p.rotation.x,p.rotation.y,p.rotation.z,p.rotation.w);}axisGroup.visible=false;markers.visible=false;debug.visible=false;return;}for(const [name,b]of Object.entries(sim.bodies)){const p=b.translation(),q=b.rotation();groups[name].position.set(p.x/S,p.y/S,p.z/S);groups[name].quaternion.set(q.x,q.y,q.z,q.w);const c=b.worldCom();comMeshes[name].position.set(c.x/S,c.y/S,c.z/S);}
 for(const mesh of meshes){mesh.material.transparent=mesh.userData.group==='base'&&$('transparent').checked;mesh.material.opacity=mesh.material.transparent?.14:1;mesh.material.depthWrite=!mesh.material.transparent;mesh.visible=!(mesh.userData.group==='rotor'&&!sim.parameters.contactEnabled&&sim.parameters.initialLid===65);}
 const bodiesFor={H:'frame',O:'frame',A:'cup',B:'lid'};for(const k of Object.keys(axes)){const name=bodiesFor[k],b=sim.bodies[name],c=cad.bodies[name].com,v=rotate(b.rotation(),cad.pivots[k].map((x,i)=>x-c[i]));axes[k].position.set(b.translation().x/S+v[0],b.translation().y/S+v[1],b.translation().z/S+v[2]);axes[k].quaternion.set(b.rotation().x,b.rotation().y,b.rotation().z,b.rotation().w);}
 axisGroup.visible=$('axes').checked;markers.visible=$('contacts').checked;const points=sim.contactMarkers.slice(0,100);for(let i=0;i<points.length;i++){if(!markerPool[i]){markerPool[i]=new THREE.Mesh(markerGeometry,markerMaterial);markers.add(markerPool[i]);}markerPool[i].position.fromArray(points[i].point);}for(let i=0;i<markerPool.length;i++)markerPool[i].visible=i<points.length;
 debug.visible=$('colliders').checked;if(debug.visible){const {vertices,colors}=sim.world.debugRender();debug.geometry.dispose();debug.geometry=new THREE.BufferGeometry();debug.geometry.setAttribute('position',new THREE.BufferAttribute(vertices.map(x=>x/S),3));debug.geometry.setAttribute('color',new THREE.BufferAttribute(colors,4));}
}
const states={precision_failed:'角度到達 ・ 数値精度不合格（成功判定を取り消し）',ready:'準備完了 · 開くを押して開始',opening:'開いています · 接触で蓋を押し上げ中',closing:'閉じています · 重力とホーン接触で戻る',opened:'65° に安定到着（±0.5° / 0.4 秒）',closed:'閉位置に安定到着（±0.5° / 0.4 秒）',hold:'保持 ・ 現在角を有限トルクで保持',unpowered:'電源断 · 重力と接触は計算を継続',incomplete:'未到達 · 14 秒以内に安定到着しませんでした'};
function updateConditionSummary(){const p=sim.parameters,contact=p.contactMode==='cad_faces'?'CAD直線部':'代表点';$('conditionSummary').textContent=`トルク上限 ${p.torqueCap.toFixed(3)} N·m / 重量倍率 ${p.lidMassScale.toFixed(1)}× / 接触モデル ${contact} / ${p.fixedBase?'固定':'自由設置'} / ${p.powered?'通電':'電源OFF'}`;}
function updateAccuracy(pass){const el=$('accuracy');el.dataset.pass=String(pass);el.textContent=`数値精度 ${pass?'合格':'不合格'} / 接触侵入 ${NUMERICAL_LIMITS.maxPenetrationMm.toFixed(2)} mm以下 / 軸ずれ ${NUMERICAL_LIMITS.maxHingeDriftMm.toFixed(2)} mm以下`;}
function uiUpdate(){const latest=replayIndex===null?sim.log.at(-1):sim.log[replayIndex];$('replay').max=Math.max(0,sim.log.length-1);$('replay').value=replayIndex??sim.log.length-1;updateConditionSummary();if(replayIndex!==null){$('target').textContent=latest.targetDeg.toFixed(2)+'°';$('servo').textContent=latest.servoDeg.toFixed(2)+'°';$('lid').textContent=latest.lidDeg.toFixed(2)+'°';$('torque').textContent=latest.torqueNm.toFixed(4)+' / '+latest.availableNm.toFixed(4);$('diagnostic').textContent=latest.penetrationMm.toFixed(3)+' / '+latest.hingeDriftMm.toFixed(3)+' mm';$('clock').textContent=latest.t.toFixed(2)+' s';$('pause').textContent=replayPlaying?'記録を一時停止':'記録を再生';$('replayPlay').textContent=replayPlaying?'記録を一時停止':'記録を再生';$('status').dataset.state='replay';$('status').textContent=`記録再生 ・ ${replayPlaying?'再生中':'一時停止中'}（接触と軸の表示はライブのみ）`;updateAccuracy(latest.numericalPass);drawGraph();return;}$('target').textContent=sim.target.toFixed(2)+'°';$('servo').textContent=sim.servoAngle().toFixed(2)+'°';$('lid').textContent=sim.lidAngle().toFixed(2)+'°';$('torque').textContent=(sim.lastTorque??0).toFixed(4)+' / '+(sim.availableTorque??0).toFixed(4);$('diagnostic').textContent=sim.peak.penetrationMm.toFixed(3)+' / '+sim.peak.hingeDriftMm.toFixed(3)+' mm';$('clock').textContent=sim.time.toFixed(2)+' s';$('pause').textContent=sim.paused?'再開':'一時停止';$('replayPlay').textContent='記録を再生';const accuracy=sim.numericalAccuracy();updateAccuracy(accuracy.pass);$('status').dataset.state=accuracy.pass?sim.command:(sim.command==='precision_failed'?'precision_failed':'numerical_invalid');$('status').textContent=(!sim.parameters.powered?'電源OFF ・ ':'')+(sim.paused?'一時停止 ・ ':'')+(states[sim.command]??sim.command)+(sim.repeat?' ・ 繰り返し '+sim.cycle:'');if(!accuracy.pass){const reasons=[];if(accuracy.penetrationFailed)reasons.push('貫通 '+NUMERICAL_LIMITS.maxPenetrationMm+' mm超');if(accuracy.hingeDriftFailed)reasons.push('軸ずれ '+NUMERICAL_LIMITS.maxHingeDriftMm+' mm超');$('status').textContent+=' / 数値精度不合格: '+reasons.join('・');}drawGraph();}
function drawGraph(){if(!sim||!$('records').open)return;const canvas=$('graph'),w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;const ratio=Math.min(devicePixelRatio,2);canvas.width=w*ratio;canvas.height=h*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const left=32,right=w-48,top=6,bottom=h-19,end=Math.max(10,replayIndex===null?sim.time:(sim.log[replayIndex]?.t??sim.time)),start=Math.max(0,end-20),span=end-start,torqueRange=Math.max(.03,sim.parameters.torqueCap);ctx.font='10px ui-monospace, Consolas, monospace';ctx.fillStyle=activePalette.mute;for(const a of [-20,0,20,40,60,80]){const y=bottom-(a+20)/100*(bottom-top);ctx.strokeStyle=activePalette.line;ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText(a+'°',0,y+3);}for(const t of [start,(start+end)/2,end]){const x=left+(t-start)/span*(right-left);ctx.fillText(t.toFixed(1)+'s',x-8,h-3);}ctx.fillStyle='#cc79a7';ctx.fillText('N·m',right+5,12);ctx.fillText(torqueRange.toFixed(3),right+5,30);ctx.fillText('0',right+5,(top+bottom)/2);ctx.fillText('-'+torqueRange.toFixed(3),right+5,bottom-2);
 for(const [key,color,dash,width]of [['targetDeg','#0072b2',[],1.5],['servoDeg','#e69f00',[6,3],1.5],['lidDeg','#009e73',[],2.5],['torqueNm','#cc79a7',[2,3],1.5]]){ctx.strokeStyle=color;ctx.setLineDash(dash);ctx.lineWidth=width;ctx.beginPath();let first=true;for(const row of sim.log){if(row.t<start||row.t>end)continue;const x=left+(row.t-start)/span*(right-left),y=key==='torqueNm'?(top+bottom)/2-row[key]/(torqueRange*2)*(bottom-top):bottom-(row[key]+20)/100*(bottom-top);first?ctx.moveTo(x,y):ctx.lineTo(x,y);first=false;}ctx.stroke();}ctx.setLineDash([]);}
function updateMode(){$('hornBiasMm').disabled=$('contactMode').value==='cad_faces';}
$('contactMode').onchange=()=>{updateMode();$('apply').textContent='接触モデルを適用して初期化';};
function live(){replayIndex=null;replayPlaying=false;}
$('replay').oninput=()=>{sim.paused=true;replayPlaying=false;replayIndex=Number($('replay').value);replayTime=sim.log[replayIndex].t;sceneUpdate();uiUpdate();};
$('replayPlay').onclick=()=>{sim.paused=true;if(replayIndex===null||replayIndex===sim.log.length-1){replayIndex=0;replayTime=sim.log[0].t;replayPlaying=true;}else replayPlaying=!replayPlaying;uiUpdate();};
$('live').onclick=()=>{live();sceneUpdate();uiUpdate();};
$('records').ontoggle=drawGraph;
function reset(parameters=getParams()){live();try{sim.reset(parameters);}catch(e){$('status').textContent='条件エラー: '+e.message;return false;}accumulator=0;lastTime=performance.now();$('apply').textContent='条件を適用して初期化';sceneUpdate();uiUpdate();return true;}
for(const command of ['open','close','repeat','stop'])$(command).onclick=()=>{live();sim.commandTo(command);uiUpdate();};$('reset').onclick=()=>reset();$('apply').onclick=()=>reset();$('pause').onclick=()=>{if(replayIndex!==null){replayPlaying=!replayPlaying;uiUpdate();return;}sim.paused=!sim.paused;accumulator=0;uiUpdate();};$('step').onclick=()=>{live();sim.paused=true;sim.step();sceneUpdate();uiUpdate();};$('poweroff').onclick=()=>{live();sim.powerOff();$('powered').checked=false;uiUpdate();};$('camera').onclick=cameraReset;
$('scenario').onchange=()=>{const p={...DEFAULTS},s=$('scenario').value;if(s==='zero')p.torqueCap=0;if(s==='no-contact')p.contactEnabled=false;if(s==='fall'){p.contactEnabled=false;p.powered=false;p.initialLid=65;}if(s==='weak'){p.torqueCap=.001;p.frontLoadG=100;}if(s==='blocked')p.shaftBlock=true;setParams(p);reset(p);};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(sim.export(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='B3_physics_conditions_log.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let accumulator=0,lastTime=performance.now(),lastUI=0;
function resize(){renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);resize();
function frame(now){const elapsed=Math.min(.08,(now-lastTime)/1000);lastTime=now;if(replayPlaying&&replayIndex!==null){replayTime+=elapsed*Number($('rate').value);while(replayIndex<sim.log.length-1&&sim.log[replayIndex+1].t<=replayTime)replayIndex++;if(replayIndex===sim.log.length-1)replayPlaying=false;}if(!sim.paused){accumulator+=elapsed*Number($('rate').value);const max=64;let steps=0;while(accumulator>=sim.parameters.dt&&steps<max){sim.step();accumulator-=sim.parameters.dt;steps++;}if(steps===max&&accumulator>.2){$('timing').textContent='計算が実時間より遅い';accumulator=Math.min(accumulator,.2);}else $('timing').textContent='固定 dt '+(sim.parameters.dt*1000).toFixed(2)+' ms';}if(now-lastUI>80){sceneUpdate();uiUpdate();lastUI=now;}controls.update();renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
addEventListener('pagehide',()=>{pauseWork();disposeTheme();},{once:true});
addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseWork();uiUpdate();}});
addEventListener('workspace:navigate',pauseWork);
globalThis.navigation?.addEventListener('navigate',pauseWork);
for(const id of ['open','close','repeat','stop','reset','apply','step','pause'])$(id).disabled=false;$('loading').textContent='ローカル計算 / 実機未検証';
window.__physics={get sim(){return sim;},cad,shapes,renderer,reset,sceneUpdate,uiUpdate,async advance(seconds){live();sim.paused=true;for(let i=0;i<Math.round(seconds/sim.parameters.dt);i++){sim.step();if(i%300===0)await new Promise(r=>setTimeout(r,0));}sceneUpdate();uiUpdate();renderer.render(scene,camera);return sim.export();}};
sceneUpdate();uiUpdate();
